#!/bin/sh

### BEGIN INIT INFO
# Provides:		openntpd
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Start openntpd at boot time
# Description:		NTP, the Network Time Protocol, is used to keep the
#			computer clocks synchronized.
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/ntpd
NAME=ntpd
DESC=openntpd

test -e /usr/sbin/openntpd || exit 0

# Include openntpd defaults if available
if [ -f /etc/default/openntpd ]
then
	. /etc/default/openntpd
fi

set -e

check_privsep_dir()
{
	# check that the privsep dir exists
	if [ ! -d /var/run/openntpd ]
	then
		mkdir /var/run/openntpd
		chmod 0755 /var/run/openntpd
	fi
}

case "$1" in
	start)
		check_privsep_dir
		echo -n "Starting $DESC: "
		start-stop-daemon --start --quiet --exec $DAEMON -- $DAEMON_OPTS
		echo "$NAME."
		;;

	stop)
		echo -n "Stopping $DESC: "
		start-stop-daemon --stop --oknodo --quiet --exec $DAEMON
		echo "$NAME."
		;;

	restart|force-reload)
		echo -n "Restarting $DESC: "
		start-stop-daemon --stop --oknodo --quiet --exec $DAEMON
		sleep 1
		check_privsep_dir
		start-stop-daemon --start --quiet --exec $DAEMON -- $DAEMON_OPTS
		echo "$NAME."
		;;

	*)
		N=/etc/init.d/$NAME
		echo "Usage: $N {start|stop|restart|force-reload}" >&2
		exit 1
		;;
esac

exit 0
