#!/bin/bash
# send_sms.sh
# /usb/bin/sms.php
NOTIFY_MSG="$NOTIFY_SHORTDATETIME;$NOTIFY_HOSTNAME: $NOTIFY_LASTHOSTSTATE$ -> $NOTIFY_HOSTSTATE$ ($NOTIFY_NOTIFICATIONTYPE$)|| $NOTIFY_HOSTOUTPUT$"

CMD="/usr/bin/sms_5c.php"
###### log to file ############
echo "$NOTIFY_SHORTDATETIME: sms.php $NOTIFY_CONTACTPAGER  $NOTIFY_MSG"
###### send SMS ############
$cmd $NOTIFY_CONTACTPAGER  "$NOTIFY_MSG"

################################################################################
# NOTIFICATION VARIABLE FOR SMS
################################################################################
#NOTIFY_CONTACTEMAIL
#NOTIFY_CONTACTNAME
#NOTIFY_CONTACTPAGER
#NOTIFY_DATE
#NOTIFY_HOSTADDRESS
#NOTIFY_HOSTALIAS
#NOTIFY_HOSTCHECKCOMMAND
#NOTIFY_HOSTDOWNTIME
#NOTIFY_HOST_EC_CONTACT
#NOTIFY_HOSTNAME
#NOTIFY_HOSTNOTIFICATIONNUMBER
#NOTIFY_HOSTOUTPUT
#NOTIFY_HOSTPERFDATA
#NOTIFY_HOSTPROBLEMID
#NOTIFY_HOST_SL
#NOTIFY_HOSTSTATE
#NOTIFY_HOSTSTATEID
#NOTIFY_HOSTTAGS
#NOTIFY_HOSTURL
#NOTIFY_LASTHOSTSTATE
#NOTIFY_LASTHOSTSTATECHANGE
#NOTIFY_LASTHOSTSTATECHANGE_REL
#NOTIFY_LASTSERVICESTATE
#NOTIFY_LASTSERVICESTATECHANGE
#NOTIFY_LOGDIR
#NOTIFY_LONGDATETIME
#NOTIFY_LONGHOSTOUTPUT
#NOTIFY_LONGSERVICEOUTPUT
#NOTIFY_MAIL_COMMAND
#NOTIFY_MONITORING_HOST
#NOTIFY_NOTIFICATIONAUTHOR
#NOTIFY_NOTIFICATIONAUTHORALIAS
#NOTIFY_NOTIFICATIONAUTHORNAME
#NOTIFY_NOTIFICATIONCOMMENT
#NOTIFY_NOTIFICATIONTYPE
#NOTIFY_OMD_ROOT
#NOTIFY_OMD_SITE
#NOTIFY_PARAMETERS
#NOTIFY_SERVICECHECKCOMMAND
#NOTIFY_SERVICEDESC
#NOTIFY_SERVICE_EC_CONTACT
#NOTIFY_SERVICENOTIFICATIONNUMBER
#NOTIFY_SERVICEOUTPUT
#NOTIFY_SERVICEPERFDATA
#NOTIFY_SERVICEPROBLEMID
#NOTIFY_SERVICE_SL
#NOTIFY_SERVICESTATE
#NOTIFY_SERVICESTATEID
#NOTIFY_SHORTDATETIME
#NOTIFY_SVC_SL
#NOTIFY_WHAT
