#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
state_txt = {
    '0': 'noStatus',
    '1': 'notRunning',
    '2': 'running'
}

def inventory_alcatel_fan(info):
    inventory = []
    for line in info:
        inventory.append((line[0], None))

    return inventory

def check_alcatel_fan(item, _no_params, info):
    for line in info:
        (fan, state) = line
        if item == fan:
            cmm_id = str((int(item[:3]) - 209))
            fan_id = item[-1]
            if state == '1':
                return 2, "CRIT - CMM %s FAN %s State is: %s(%s)" % (cmm_id, fan_id, state_txt[state], state)
            if state == '2':
                return 0, "OK - CMM %s FAN %s State is: %s(%s)" % (cmm_id, fan_id, state_txt[state], state)
    return 3, "FAN not found"

check_info["alcatel.fan"] = {
    "check_function"        : check_alcatel_fan,
    "inventory_function"    : inventory_alcatel_fan,
    "service_description"   : "FAN %s",
    "has_perfdata"          : False,
    "snmp_scan_function"    : lambda oid: oid(".1.3.6.1.2.1.1.1.0").startswith("Alcatel-Lucent OS6900-X40"),
    "snmp_info"             : (".1.3.6.1.4.1.6486.801.1.1.1.3.1.1.11.1", [OID_END, '2']),
}

