#!/bin/bash
if [ ! -f /opt/xensource/bin/xe ];then
  exit
fi
echo "<<<xen>>>"
xl info | sed -nr '/free_memory|total_memory/p'
xe host-license-view | sed -n '1,8p' | sed -nr 's/^\s+//p'
echo "patches: $(xe patch-list params=name-label --minimal | tr ',' ' ')"
