#!/bin/bash
if ! type iotop > /dev/null ;then
  echo "iotop Not Found !" && exit 3
fi
PID=`pidof $1`
if [ ! -z "$PID" ];then
   DATA_READ=$(iotop -n 1 -b -p $PID -qqq | awk -F ' ' '{print $4}')
   DATA_WRITE=$(iotop -n 1 -b -p $PID -qqq | awk -F ' ' '{print $6}')
   PERF_DATA="OK |data_read=${DATA_READ} B/s;;; data_write=${DATA_WRITE} B/s;;;"
   echo "$PERF_DATA" && exit 0
else
  echo "PROC $1 Not Found !" && exit 3
fi
