#!/bin/bash

GW=$(route -n | grep ^0 | awk '{print $2}')

if [ -d /usr/lib64/nagios/plugins ];then
  PLUGINS="/usr/lib64/nagios/plugins/"
elif [ -d /usr/lib/nagios/plugins ];then
  PLUGINS="/usr/lib/nagios/plugins/"
else
  exit 1
fi
${PLUGINS}/check_icmp $GW
