#!/bin/bash
# check xenserver vm's xs-tools is up-to-date or lost on current host
# TODO: detect VM's UUID changed if crashed and restart on other host
test -d /opt/xensource || exit
current_host_id() {
  hostname=`hostname`
  xe host-list --minimal hostname=$hostname
}

vm_out_of_date() {
  host_id=`current_host_id`
  xe vm-list PV-drivers-up-to-date=false params=name-label --minimal is-control-domain=false resident-on=$host_id
}

vm_lost_xs_tools() {
  host_id=`current_host_id`
  xe vm-list PV-drivers-up-to-date='<not in database>' params=name-label --minimal is-control-domain=false resident-on=$host_id
}

crit_vm=`vm_lost_xs_tools`
warn_vm=`vm_out_of_date`

if [ ! -z "$crit_vm" ];then
  if [ ! -z "$warn_vm" ];then
    echo "lost: $crit_vm; out-of-date: $warn_vm" && exit 2
  else
    echo "lost: $crit_vm" && exit 2
  fi
elif [ ! -z "$warn_vm" ];then
  echo "out-of-date: $warn_vm" && exit 1
else
  echo "all VM's xs-tools up-to-date" && exit 0
fi
