#!/bin/bash
if ! lsmod | grep ipmi_si -q;then
    echo "kernel module lost: ipmi_si"
    exit 1
fi

if ! which ipmitool > /dev/null;then
    echo "command not found: ipmitool"
    exit 1
fi

if ! type rmcpping > /dev/null;then
    echo "command not found: rmcpping"
    exit 1
fi

IPMI_IP=$(ipmitool lan print |egrep '^IP Address *:' | cut -d ':' -f2 |  sed -n 's/\s*//gp')
if [ -z $IPMI_IP ];then
    echo "3 IPMI.IP IP=$IPMI_IP;-;-;-; UNKNOWN - IPMI.IP LOST"
fi

COUNT=3
if rmcpping -c $COUNT $IPMI_IP > /dev/null;then
    echo "0 IPMI.IP IP=$IPMI_IP;-;-;-; OK - IPMI.IP: $IPMI_IP"
else
    echo "2 IPMI.IP IP=$IPMI_IP;-;-;-; UNKNOWN - IPMI.IP: $IPMI_IP Unreacheable"
fi
