#!/bin/bash
# check xenserver vm's xs-tools is up-to-date or lost on current host
# TODO: detect VM's UUID changed if crashed and restart on other host
test -d /opt/xensource || exit

current_host_id() {
  hostname=`hostname`
  xe host-list --minimal hostname=$hostname
}

vm_out_of_date() {
  host_id=`current_host_id`
  xe vm-list PV-drivers-up-to-date=false params=name-label --minimal is-control-domain=false resident-on=$host_id
}

vm_lost_xs_tools() {
  host_id=`current_host_id`
  xe vm-list PV-drivers-up-to-date='<not in database>' params=name-label --minimal is-control-domain=false resident-on=$host_id
}

crit_vm=`vm_lost_xs_tools`
warn_vm=`vm_out_of_date`

if [ ! -z "$crit_vm" ];then
  if [ ! -z "$warn_vm" ];then
    STATETEXT="pv=${#crit_vm};3;5; LOST=$crit_vm;OUT-OF-DATE=$warn_vm"
  else
    STATETEXT="pv=${#crit_vm};3;5; LOST=$crit_vm"
  fi
  STATE=2
elif [ ! -z "$warn_vm" ];then
  STATE=1
  STATETEXT="pv=${#warn_vm};3;5; OUT-OF-DATA=$warn_vm'"
else
  STATE=0
  STATETEXT="pv=0;3;5; VM's PV state OK"
fi

echo "$STATE xs-tools $STATETEXT"
