#!/bin/bash
service salt-master status | grep -q pid
if [ ! $? ];then
   exit
fi

minions=$(salt-key -l acc | sed -n '2,$p' | tr '\n' ' ')
down_counts=0
for minion in $minions
do
    state=$(salt "$minion" test.ping --out txt | sed -nr 's/\s+//p' | cut -d ':' -f2)
    if [ ! x"$state" = "xTrue" ];then
        minions_down="$minions_down $minion"
        let down_counts=down_counts+1
    fi
done

if [ ${down_counts} -gt 0 ];then
    echo "1 minions_state minions_down=$down_counts;-;-;-; WARN - test.ping failed: ${minions_down}"
fi
